name: swim-explorer
dependencies:
  - python
  - pytest
  - pytest-cov
  - pyyaml
  - pip:
    - uwsgi
    - gevent
    - gevent-websocket
    - gunicorn
    - flask-socketio
    - websockets
    - geojson
    - git+https://git@bitbucket.org/antavelos-eurocontrol/subscription-manager-client.git
    - git+https://git@bitbucket.org/antavelos-eurocontrol/rest-client.git
    - git+https://git@bitbucket.org/antavelos-eurocontrol/swim-pubsub.git
    - python-qpid_proton
