name: swim-explorer
dependencies:
  - python
  - pytest
  - pytest-cov
  - pyyaml
  - pip:
    - gevent
    - gevent-websocket
    - gunicorn
    - flask-socketio
    - websockets
    - geojson
    - git+https://git@github.com/eurocontrol-swim/subscription-manager-client.git
    - git+https://git@github.com/eurocontrol-swim/rest-client.git
    - git+https://git@github.com/eurocontrol-swim/swim-pubsub.git
    - python-qpid_proton
